RUBY PROJECT : Enumerables
khalilhamdii/Ruby_Enumerables pull request #1
Opened 2020-09-17 14:29 UTC by khalilhamdii

This project is built using the Ruby language. We created methods that work that same as Ruby enumerable such as ( Each, Each_with_index, Select, all?, none, any?, count, map and inject ).

2020-09-17 18:47 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for the job done so far
However, there are some issues.
Kindly read the comments left below, make sure you passed the tests and then submit a new code review request
Thanks

Mael FOSSO

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :042 > block = proc { |num| num < 4 }
2.6.5 :043 > array.my_each_with_index(&block)
 => 0...100 
2.6.5 :044 > array.each_with_index(&block)
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :045 > 
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :047 > block = proc { |num| num < 4 }
2.6.5 :048 > range = Range.new(5, 50) 
2.6.5 :049 > range.my_each_with_index(&block)
 => 0...46 
2.6.5 :050 > range.each_with_index(&block)
 => 5..50 
2.6.5 :051 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :052 > array
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :053 > array.select.is_a?(Enumerator)
 => true 
2.6.5 :054 > array.my_select.is_a?(Enumerator)
Traceback (most recent call last):
       11: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       10: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        6: from (irb):54
        5: from main.rb:26:in `my_select'
        4: from main.rb:7:in `my_each'
        3: from main.rb:7:in `each'
        2: from main.rb:8:in `block in my_each'
        1: from main.rb:27:in `block in my_select'
LocalJumpError (no block given (yield))
2.6.5 :055 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :057 > array
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :058 > array.my_all?(3)
 => true 
2.6.5 :059 > array.all?(3)
 => false 
2.6.5 :060 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :062 > words = %w[dog door rod blade]
2.6.5 :063 > words.my_any?('cat')
 => true 
2.6.5 :064 > words.any?('cat')
 => false 
2.6.5 :065 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :067 > words = %w[dog door rod blade]
2.6.5 :068 > words.my_none?(5)
 => false 
2.6.5 :069 > words.none?(5)
 => true 
2.6.5 :070 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :072 > range = Range.new(5, 50) 
2.6.5 :073 > range.my_count
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):73
        1: from main.rb:95:in `my_count'
NameError (undefined local variable or method `length' for 5..50:Range)
2.6.5 :074 > range.count
 => 46 
2.6.5 :075 > 
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :077 > array
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :078 > array.my_map.is_a?(Enumerator)
Traceback (most recent call last):
       11: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       10: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        6: from (irb):78
        5: from main.rb:102:in `my_map'
        4: from main.rb:17:in `my_each_with_index'
        3: from main.rb:17:in `each'
        2: from main.rb:18:in `block in my_each_with_index'
        1: from main.rb:106:in `block in my_map'
NoMethodError (undefined method `call' for nil:NilClass)
2.6.5 :079 > array.map.is_a?(Enumerator)
 => true 
2.6.5 :080 > 
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +  end
```rb
2.6.5 :082 > my_proc = proc { |num| num > 10 }
2.6.5 :083 > array.my_map(my_proc) { |num| num < 10 }
 => [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true] 
2.6.5 :084 > array.my_map(&my_proc)
 => [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] 
2.6.5 :085 > 
```
It should execute only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :088 > search = proc { |memo, word| memo.length > word.length ? memo : word }
2.6.5 :089 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :090 > words.my_inject(&search)
Traceback (most recent call last):
       12: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       11: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
       10: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        7: from (irb):90
        6: from main.rb:115:in `my_inject'
        5: from main.rb:7:in `my_each'
        4: from main.rb:7:in `each'
        3: from main.rb:8:in `block in my_each'
        2: from main.rb:116:in `block in my_inject'
        1: from (irb):85:in `block in irb_binding'
NoMethodError (undefined method `length' for 0:Integer)
2.6.5 :091 > words.inject(&search)
 => "blade" 
2.6.5 :092 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :095 > array
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :096 > array.my_inject(:+)
Traceback (most recent call last):
       11: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       10: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        6: from (irb):96
        5: from main.rb:115:in `my_inject'
        4: from main.rb:7:in `my_each'
        3: from main.rb:7:in `each'
        2: from main.rb:8:in `block in my_each'
        1: from main.rb:116:in `block in my_inject'
LocalJumpError (no block given (yield))
2.6.5 :097 > array.inject(:+)
 => 378 
2.6.5 :098 > 
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :100 > range = Range.new(5, 50) 
2.6.5 :101 > range.my_inject(:*)
Traceback (most recent call last):
       11: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
       10: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        6: from (irb):101
        5: from main.rb:115:in `my_inject'
        4: from main.rb:7:in `my_each'
        3: from main.rb:7:in `each'
        2: from main.rb:8:in `block in my_each'
        1: from main.rb:116:in `block in my_inject'
LocalJumpError (no block given (yield))
2.6.5 :102 > range.inject(:*)
 => 1267253883404724085150525340252698701849068398706688000000000000 
2.6.5 :103 > 
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :105 > array
 => [5, 3, 3, 2, 4, 8, 3, 6, 5, 0, 1, 5, 1, 4, 0, 1, 0, 4, 0, 8, 4, 8, 6, 7, 8, 4, 0, 0, 6, 1, 0, 8, 4, 0, 6, 2, 4, 6, 0, 5, 3, 0, 2, 3, 4, 8, 7, 5, 6, 8, 8, 3, 0, 8, 3, 1, 8, 4, 4, 2, 6, 6, 2, 5, 6, 4, 4, 2, 3, 2, 7, 7, 1, 8, 2, 5, 4, 8, 7, 3, 1, 0, 5, 7, 1, 5, 1, 5, 1, 5, 1, 0, 0, 8, 7, 1, 1, 1, 4, 3] 
2.6.5 :106 > array.my_inject(20, :*)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):106
        1: from main.rb:114:in `my_inject'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
2.6.5 :107 > array.inject(20, :*)
 => 0 
2.6.5 :108 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :110 > range = Range.new(5, 50) 
2.6.5 :111 > range.my_inject(2, :*)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):111
        1: from main.rb:114:in `my_inject'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
2.6.5 :112 > range.inject(2, :*)
 => 2534507766809448170301050680505397403698136797413376000000000000 
2.6.5 :113 >
```

2020-09-17 18:47 UTC, maelfosso commented on main.rb
> +end
```rb
2.6.5 :115 > actual = multiply_els [2, 4, 5]
2.6.5 :116 > actual == 40
 => false 
2.6.5 :117 > 
```

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:11 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:12 UTC, khalilhamdii commented on main.rb
> +  end
Errors fixed

2020-09-18 22:12 UTC, khalilhamdii commented on main.rb
> +end
Errors fixed

2020-09-18 22:12 UTC, khalilhamdii commented on main.rb
> +end
Errors fixed

2020-09-18 22:15 UTC, khalilhamdii commented
Thank you very much for your review, it was really helpful! We managed to fix all the errors and pass the required tests.

2020-09-18 23:25 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE!👏 👏 👏  There are just a few issues that need to be resolved before you can move on. Please take a look at the following methods:⬇️ 
****

- my_all?
- my_any?
- my_none?
- my_inject

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

2020-09-18 23:25 UTC, BrittanyBlake commented on main.rb
> +  end
- [ ] When no block or argument is given, `my_all?` should return true if none of the elements in the collection are false or nil:
```ruby 
[1, "hi", true, []].all? === [1, "hi", true, []].my_all? => false
```

2020-09-18 23:25 UTC, BrittanyBlake commented on main.rb
> +  end
- [ ] When no block or argument is given, `my_any?` should return false if at least one of the elements in the collection is not true:
```ruby
[ nil, false].any? === [  nil, false].my_any? => false
```

2020-09-18 23:25 UTC, BrittanyBlake commented on main.rb
> +  end
- [ ] When a pattern other than a Regex or a Class is given, `my_none?` should return false only if one of the collection matches the pattern. 
```ruby
[3, 4, 7, 11].my_none?(4) === [3, 4, 7, 11].none?(4) => false
```

2020-09-18 23:25 UTC, BrittanyBlake commented on main.rb
> +end
- [ ] If no block or argument is given, `my_inject` should **raise** a `LocalJumpError`. You are not currently raising any error.

2020-09-19 12:44 UTC, khalilhamdii commented on main.rb
> +  end
Issue fixed

2020-09-19 12:44 UTC, khalilhamdii commented on main.rb
> +  end
Issue fixed

2020-09-19 12:45 UTC, khalilhamdii commented on main.rb
> +  end
Issue fixed

2020-09-19 12:45 UTC, khalilhamdii commented on main.rb
> +end
Issue fixed

2020-09-19 12:46 UTC, khalilhamdii commented
Thank you for your second review, it was really helpful! We managed to fix all the issues and pass the required tests.

2020-09-19 15:55 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @khalilhamdii and @Adewunmi97 :lollipop: :balloon: 

### Thank you for doing the changes requested by the previous reviewers :medal_sports: :medal_sports: all your enumerable methods are working correctly so please feel proud of all the hard work you put into this project, that being said there's just one method still not retrieving the right answer so let's work on it shall we? :construction: :construction_worker: :construction_worker_woman: 

#### my_inject

- [ ] Raises a "LocalJumpError" when no block or argument is given

```ruby
[2,5,3].my_inject == [2,5,3].inject => LocalJumpError (no block given)
```
- Yours retrieves a message but not a Ruby Error (wrong answer)
![image](https://user-images.githubusercontent.com/52209067/93671107-7e888480-fa5d-11ea-8377-bc8dce911b46.png)

- Real inject retrieves a LocalJumpError (right answer)
![image](https://user-images.githubusercontent.com/52209067/93632451-96530080-f9aa-11ea-8c8c-7115a17aedcd.png)

### That's it, team! :raised_hands: 

### Please :pray: work on it :technologist: :woman_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-09-19 15:55 UTC, euqueme commented on main.rb
> +  end
#### [OPTIONAL]
I think we could get the block of my_none? from my_any? we should only do something like !my_any? for my_none? to work. For example:

```ruby
def my_none?(arg = nil, &block)
  !my_any?(arg, &block)
end
```

To make this work we have to use block.call(element) instead of yield(element) in my_any?

2020-09-19 17:02 UTC, khalilhamdii commented on main.rb
> +  end
Thank you for this advice it's really helpful!

2020-09-19 17:12 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🤩 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-09-19 17:15 UTC, merged